name: flutter_map_interactive
description: "A powerful Flutter Map plugin adding collision detection, interactive editing (drag, rotate, resize, undo/redo), and state management for markers, polylines, and image overlays."
version: 0.1.0
homepage: https://github.com/mkidv/flutter_map_interactive
repository: https://github.com/mkidv/flutter_map_interactive
issue_tracker: https://github.com/mkidv/flutter_map_interactive/issues

topics:
  - flutter-map
  - map
  - collision-detection
  - interactive
  - geo

environment:
  flutter: ">=3.2.0"
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  collection: ^1.19.1
  flutter:
    sdk: flutter
  flutter_map: ^8.3.2
  latlong2: ^0.9.1
  meta: ^1.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  fake_async: ^1.3.2
